[package]
name = "core"
version = "0.0.1"
authors = ["East Agile <open-source@eastagile.com>"]
description = "The application core code"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

rand = "0.7.3"
log = "0.4.17"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["yaml"]
